"""Paletas semánticas compartidas por la interfaz VESP."""

from services.assets import ruta_asset


def _palette(
    *,
    bg_gradient_start: str,
    bg_gradient_end: str,
    surface: str,
    surface_alt: str,
    border: str,
    text_primary: str,
    text_secondary: str,
    text_disabled: str,
    accent: str,
    accent_hover: str,
    accent_hover_text: str,
    accent_text: str,
    success: str,
    warning: str,
    danger: str,
    danger_button_bg: str,
    danger_button_hover: str,
    danger_button_text: str,
    card_contrast: str,
    sidebar_active_bg: str,
    shadow: str,
    logo_path: str,
) -> dict[str, str]:
    return {
        "bg_gradient_start": bg_gradient_start,
        "bg_gradient_end": bg_gradient_end,
        "surface": surface,
        "surface_alt": surface_alt,
        "border": border,
        "text_primary": text_primary,
        "text_secondary": text_secondary,
        "text_disabled": text_disabled,
        "accent": accent,
        "accent_hover": accent_hover,
        "accent_hover_text": accent_hover_text,
        "accent_text": accent_text,
        "success": success,
        "warning": warning,
        "danger": danger,
        "danger_button_bg": danger_button_bg,
        "danger_button_hover": danger_button_hover,
        "danger_button_text": danger_button_text,
        "card_contrast": card_contrast,
        "sidebar_active_bg": sidebar_active_bg,
        "shadow": shadow,
        "logo_path": ruta_asset(logo_path),
        "radius_sm": "6px",
        "radius_md": "10px",
        "radius_lg": "14px",
        "radius_card": "18px",
        "spacing_xs": "4px",
        "spacing_sm": "8px",
        "spacing_md": "12px",
        "spacing_lg": "18px",
        "spacing_xl": "24px",
        "font_size_xs": "10px",
        "font_size_sm": "12px",
        "font_size_md": "13px",
        "font_size_lg": "16px",
        "font_size_title": "22px",
        "font_size_display": "28px",
        "control_height": "34px",
        "table_row_height": "36px",
        "scrollbar_width": "8px",
        "border_width": "1px",
    }


CLARO = _palette(
    bg_gradient_start="#FFFFFF",
    bg_gradient_end="#E8F0E6",
    surface="rgba(255, 255, 255, 232)",
    surface_alt="#F3F6F2",
    border="rgba(35, 31, 32, 48)",
    text_primary="#231F20",
    text_secondary="#565152",
    text_disabled="#625D5E",
    accent="#0E7F09",
    accent_hover="#0A6506",
    accent_hover_text="#FFFFFF",
    accent_text="#FFFFFF",
    success="#0E7F09",
    warning="#805500",
    danger="#B42318",
    danger_button_bg="#B42318",
    danger_button_hover="#912018",
    danger_button_text="#FFFFFF",
    card_contrast="#E1F0DF",
    sidebar_active_bg="#0E7F09",
    shadow="rgba(0, 0, 0, 42)",
    logo_path="assets/vespLogoDarkGreen.svg",
)

VERDE = _palette(
    bg_gradient_start="#0E7F09",
    bg_gradient_end="#075704",
    surface="rgba(35, 31, 32, 218)",
    surface_alt="#1C401A",
    border="rgba(255, 255, 255, 72)",
    text_primary="#FFFFFF",
    text_secondary="#EAF5E9",
    text_disabled="#F2F2F2",
    accent="#FFFFFF",
    accent_hover="#60BA5A",
    accent_hover_text="#231F20",
    accent_text="#0E7F09",
    success="#D7F5D4",
    warning="#FFF2CC",
    danger="#FFB4AB",
    danger_button_bg="#FFB4AB",
    danger_button_hover="#FAD3CE",
    danger_button_text="#231F20",
    card_contrast="rgba(96, 186, 90, 76)",
    sidebar_active_bg="#FFFFFF",
    shadow="rgba(0, 0, 0, 72)",
    logo_path="assets/vespLogoLight.svg",
)

NEGRO = _palette(
    bg_gradient_start="#000000",
    bg_gradient_end="#231F20",
    surface="rgba(35, 31, 32, 232)",
    surface_alt="#141313",
    border="rgba(96, 186, 90, 100)",
    text_primary="#FFFFFF",
    text_secondary="#D8D5D6",
    text_disabled="#AAA6A7",
    accent="#60BA5A",
    accent_hover="#83D67D",
    accent_hover_text="#000000",
    accent_text="#000000",
    success="#60BA5A",
    warning="#FFD166",
    danger="#FF8A80",
    danger_button_bg="#FF8A80",
    danger_button_hover="#FFB4AB",
    danger_button_text="#000000",
    card_contrast="rgba(96, 186, 90, 56)",
    sidebar_active_bg="#60BA5A",
    shadow="rgba(0, 0, 0, 110)",
    logo_path="assets/vespLogoLight.svg",
)

GRAFITO = _palette(
    bg_gradient_start="#231F20",
    bg_gradient_end="#171516",
    surface="rgba(49, 44, 45, 232)",
    surface_alt="#302B2C",
    border="rgba(96, 186, 90, 88)",
    text_primary="#FFFFFF",
    text_secondary="#D8D5D6",
    text_disabled="#B8B4B5",
    accent="#60BA5A",
    accent_hover="#83D67D",
    accent_hover_text="#231F20",
    accent_text="#231F20",
    success="#60BA5A",
    warning="#FFD166",
    danger="#FF8A80",
    danger_button_bg="#FF8A80",
    danger_button_hover="#FFB4AB",
    danger_button_text="#231F20",
    card_contrast="rgba(96, 186, 90, 56)",
    sidebar_active_bg="#60BA5A",
    shadow="rgba(0, 0, 0, 96)",
    logo_path="assets/vespLogoLight.svg",
)

THEMES = {
    "Claro": CLARO,
    "Verde": VERDE,
    "Negro": NEGRO,
    "Grafito": GRAFITO,
}
